name: Build Oras .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release  --version-suffix pre-${{ github.run_number }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oras.1.0.4.nupkg
          path: Oras/bin/Release/Oras.1.0.4.nupkg
          compression-level: 0
          
            
